name: Update submodule pointer
on:
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: Sync submodule
        run: git submodule sync --recursive

      - name: Fetch remote branches
        run: git submodule foreach 'git fetch --all'

      - name: Checkout dist branch
        run: |
          cd third-party/build-deps
          git switch dist || git switch -c dist --track origin/dist
          git pull
          cd ../..

      - name: Commit pointer
        run: |
          git config user.name "${{ secrets.GH_NAME }}"
          git config user.email "${{ secrets.GH_EMAIL }}"
          git add third-party/build-deps
          git commit -m "Update submodule pointer" || echo "No changes"

      - name: Push
        run: git push
